# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sample5' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sample5
  pod 'Socket.IO-Client-Swift'

  target 'sample5Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sample5UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
